version: '3'
services:
  app:
    build: .
    ports:
      - 19000:19000
      - 19001:19001
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start 
    networks:
      - avaleasy-net
networks:
  avaleasy-net:
    external:
      name: avaleasy-net
