version: '3.5'
services:
  app:
    container_name: avaleasy-app
    privileged: true
    image: avaleasy/avaleasy-app:1.0.0
    command: sh -c "yarn install && yarn start"
    ports:
      - 19000:19000
      - 19001:19001
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - avaleasy-net
    external_links:
      - avaleasy-backend

networks:
  avaleasy-net:
      name: avaleasy-net
      external: true
